### ISSUE TITLE
vim-dasht ignores DASHT_DOCSETS_DIR

### ISSUE THREAD

**Issue by laoshaw** [sunaku/vim-dasht#16]
I'm sharing docsets between zeal and dasht by setting DASHT_DOCSETS_DIR to zeal's docsets, dasht works fine in the terminal, however inside vim, it's not working(this setting is ignored).

**Comment by laoshaw** [comment]
if I symlink Zeal's docsets to dasht's default directory, it does not work either.

the difference between Zeal and dasht's docsets are that, Zeal does not require tgz file in docset directory.

**Comment by sunaku** [comment]
Try setting the `DASHT_DOCSETS_DIR` environment variable in your shell configuration file (such as your `~/.profile`) so that it's applied to your entire session.  This way, both `dasht` and `vim` will inherit it.

Regarding interoperability with Zeal, I have created a new issue https://github.com/sunaku/dasht/issues/52 to track it.  Thanks!

**Comment by mattkatz** [comment]
Just some feedback here - I started using dasht and I've set the DASHT_DOCSETS_DIR to be the Zeal docsets directory. Dasht works for me and the missing .tgz files don't seem to matter.
