### ISSUE TITLE
Builtin Vim alternative for Keyword/Selection Lookup

### ISSUE THREAD

**Issue by Konfekt** [sunaku/vim-dasht#3]
Hello,

How about the following alternative, using `&keywordprg` ? 

``` vim
setlocal keywordprg=dasht\ lua:\
nnoremap <buffer> K K<CR>
xnoremap <buffer> K K<CR>
```

See https://github.com/KabbAmine/zeavim.vim/issues/7.

**Comment by sunaku** [comment]
:+1: Good idea, but in NeoVim, setting it to an external command (such as `echo`) causes NeoVim to execute that `keywordprg` with `:!` (as opposed to `:terminal`) which has the disadvantage that `keywordprg` is no longer interactive: the output of `keywordprg` is read and displayed in one shot. :scream:

**Comment by Konfekt** [comment]
Ah, then NeoVim is not for me. Is that a feature or bug? For example, `:!tig status` is a fast alternative to fugitive's `:Git` and I'd miss it dearly.

**Comment by Konfekt** [comment]
Perhaps `keywordprg` is an edge case where it simply does not work out and it should be discussed in an issue at NeoVim. To boot, the annoyance by having to hit `<CR>` shows that also in Vim, the interactivity is somewhat accidental.

**Comment by sunaku** [comment]
`:!` is a blocking command in Vim: you can't do anything in Vim until that command finishes.  In contrast, NeoVim has a more powerful pseudo-terminal emulator (launched via `:terminal` or `termopen()`, which is what I use in this plugin) that lets you run commands in a terminal side by side with NeoVim.  As a result, the traditional `:!` method becomes less appealing (because it's a blocking operation) in NeoVim. :neckbeard:

**Comment by Konfekt** [comment]
Yeah, but then NeoVim should be able to distinghish between `:!` and `:terminal` for `keywordprg`. Perhaps passing it to `keywordprg` optionally, say `keywordprg=:terminal dasht`.
